### ISSUE TITLE
Не определяются картинки по https ссылкам

### ISSUE THREAD

**Issue by astarcev** [Vizakenjack/ok#2]
Не работает подгрузка картинок по https

**Comment by Vizakenjack** [comment]
На какой странице? Какой браузер, ОС? у меня все норм вроде бы.

**Comment by astarcev** [comment]
@Vizakenjack и правда, пробую еще раз — всё ок. Воспроизводилось на странице добавления картинки, выводилось предупреждение о том, что изображение не найдено. Ссылка была вида https://pp.vk.me///
